apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: webapi-deployment 
spec: 
  selector: 
    matchLabels: 
      app: web 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: web 
    spec: 
      containers: 
      - name: webapi 
        image: autodeploy.azurecr.io/csandhya8/springbootmavenjunitsample:#{Release.Artifacts.Springbootmavenjunitsample.BuildId}#
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: autodeploy      
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: web-service 
spec: 
  selector: 
    app: web 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer
